#!/bin/sh

case "$1" in
    start)
        start
    ;;
    stop)
        stop
    ;;
    status)
        status
    ;;
    restart)
        stop
        start
        ;;
    *)
        echo "usage: ./xstack.d <start|stop|restart|status>"
        exit 1
        ;;
esac
exit $?
